# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- develop

pool:
  vmImage: ubuntu-latest

container: mcr.microsoft.com/playwright:focal

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.17.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    npm run lint
  displayName: 'npm run lint'

- script: |
    npm test
  displayName: 'npm test'

- script: |
    npm run build
  displayName: 'npm build'

- publish: $(System.DefaultWorkingDirectory)/build
  artifact: WebAppBuild

- task: AzureStaticWebApp@0
  inputs:
    app_location: '$(System.DefaultWorkingDirectory)'
    output_location: '$(System.DefaultWorkingDirectory)/build'
  env:
    azure_static_web_apps_api_token: $(deployment_token)